[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
